const service_plans_data = [
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'large',
            readWriteMix: 'write-mostly',
        },
        meta: {
            id: 'bde43d46-6c58-4928-8e46-cd0a6e47a734',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.757-08:00',
            timeModified: '2017-11-21T09:47:11.757-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'Streaming Backup: large streams of data that are rarely accessed',
        name: 'Backup',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '100ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'medium',
            readWriteMix: 'write-mostly',
        },
        meta: {
            id: 'ad3b2498-405b-40e8-a4f0-518cb34fd4ca',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.758-08:00',
            timeModified: '2017-11-21T09:47:11.758-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'Database Log: logs for databases of all types',
        name: 'DB Log',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'medium',
            readWriteMix: 'read-mostly',
        },
        meta: {
            id: 'fb4f2fef-447f-46f8-b141-db10cf94ad15',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.759-08:00',
            timeModified: '2017-11-21T09:47:11.759-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'DSS Data: Design Support System and Analytics Databases',
        name: 'DSS Data',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '8ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '26d0be75-25fd-454e-b927-ade853b27c29',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.759-08:00',
            timeModified: '2017-11-21T09:47:11.759-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'Traditional Virtualized Application: virtualized service and file-based applications',
        name: 'General Virtualized Applications',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '8ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '92d65fee-8d93-4722-b6fe-1053381f25d1',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.760-08:00',
            timeModified: '2017-11-21T09:47:11.760-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'OLTP Data',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'large',
            readWriteMix: 'write-mostly',
        },
        meta: {
            id: '35be2dfd-eb82-48ea-a2fc-348cdd80add6',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.761-08:00',
            timeModified: '2017-11-21T09:47:11.761-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description: 'Online Archive: large amounts of data that are infrequently accessed',
        name: 'Online Archive',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '100ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'medium',
            readWriteMix: 'read-write',
        },
        meta: {
            id: 'e0b835a4-219f-442d-83fc-eeb0c5aacc09',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:47:11.762-08:00',
            timeModified: '2017-11-21T09:47:11.762-08:00',
            version: 1,
        },
        state: 'PUBLISHED',
        accounts: [],
        description:
            'Technical Applications: large amounts of data held in many small files, with a need for high-throughput processing',
        name: 'Technical Applications',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '8ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '83c30403-76d8-4482-9afe-e6d068aec28f',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:48:07.486-08:00',
            timeModified: '2017-11-21T09:48:07.486-08:00',
            version: 1,
        },
        sourceServicePlanId: '92d65fee-8d93-4722-b6fe-1053381f25d1',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'Marketing DB',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '00a472d2-2dcf-4406-babc-49b82b816832',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:48:12.639-08:00',
            timeModified: '2017-11-21T09:48:12.639-08:00',
            version: 1,
        },
        sourceServicePlanId: '92d65fee-8d93-4722-b6fe-1053381f25d1',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'Sales DB',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'medium',
            readWriteMix: 'write-mostly',
        },
        meta: {
            id: 'e68c592b-35f8-4c32-a173-4850b7f3785a',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:48:18.618-08:00',
            timeModified: '2017-11-21T09:48:18.618-08:00',
            version: 1,
        },
        sourceServicePlanId: 'ad3b2498-405b-40e8-a4f0-518cb34fd4ca',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'Database Log: logs for databases of all types',
        name: 'Marketing Logs',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'sequential',
            ioSize: 'medium',
            readWriteMix: 'write-mostly',
        },
        meta: {
            id: '8044932b-1178-4acc-9830-f9ec4eb06a2c',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:48:23.699-08:00',
            timeModified: '2017-11-21T09:48:23.699-08:00',
            version: 1,
        },
        sourceServicePlanId: 'ad3b2498-405b-40e8-a4f0-518cb34fd4ca',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'Database Log: logs for databases of all types',
        name: 'Sales Logs',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '770ab553-ad09-441c-9911-ec4535c412c8',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:48:38.984-08:00',
            timeModified: '2017-11-21T09:48:38.984-08:00',
            version: 1,
        },
        sourceServicePlanId: '26d0be75-25fd-454e-b927-ade853b27c29',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'Traditional Virtualized Application: virtualized service and file-based applications',
        name: 'Corporate Web Services',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '8ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: 'df53bac2-2518-418a-92b7-44ccdb6e2b4a',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:50:23.589-08:00',
            timeModified: '2017-11-21T09:50:23.589-08:00',
            version: 1,
        },
        sourceServicePlanId: '92d65fee-8d93-4722-b6fe-1053381f25d1',
        state: 'UNPUBLISHED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'UnpublishedData',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: '9418aee1-9fa1-4ccc-a4cf-a7dee955e1e4',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:50:29.457-08:00',
            timeModified: '2017-11-21T09:50:42.678-08:00',
            version: 2,
        },
        sourceServicePlanId: '92d65fee-8d93-4722-b6fe-1053381f25d1',
        state: 'PUBLISHED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'PublishedData',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
    {
        ioCategory: {
            ioPattern: 'random',
            ioSize: 'small',
            readWriteMix: 'read-write',
        },
        meta: {
            id: 'ad73c80d-09f1-4176-8383-f42ee8fb9ef4',
            objType: 'ServicePlan',
            timeCreated: '2017-11-21T09:50:32.514-08:00',
            timeModified: '2017-11-21T09:51:29.954-08:00',
            version: 3,
        },
        sourceServicePlanId: '92d65fee-8d93-4722-b6fe-1053381f25d1',
        state: 'RETIRED',
        accounts: [],
        description: 'OLTP Data: Online Transactional Processing Databases',
        name: 'RetiredData',
        slos: {
            Availability: {
                kind: 'STRING',
                value: '99.999%',
                immutable: true,
            },
            RPO: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            'Response Time': {
                kind: 'STRING',
                value: '5ms',
                immutable: true,
            },
            Retention: {
                kind: 'STRING',
                value: 'N/A',
                immutable: true,
            },
            Security: {
                kind: 'STRING',
                value: 'No Encryption',
                immutable: true,
            },
        },
        tags: [],
    },
];
