// Copyright 2019 Tad Lebeck
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Modal Actions
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

// Table Actions
export const ADD_SELECTED_ROW = 'ADD_SELECTED_ROW';
export const ADD_SELECTED_ROWS = 'ADD_SELECTED_ROWS';
export const REMOVE_SELECTED_ROW = 'REMOVE_SELECTED_ROW';
export const REMOVE_ALL_SELECTED_ROWS = 'REMOVE_ALL_SELECTED_ROWS';
export const CARDS_MODE = 'CARDS_MODE';
export const CARDS_COLLAPSED = 'CARDS_COLLAPSED';
export const CARDS_EXPANDED = 'CARDS_EXPANDED';
export const TABLE_MODE = 'TABLE_MODE';
export const TABLE_MOUNT = 'TABLE_MOUNT';
export const TABLE_UNMOUNT = 'TABLE_UNMOUNT';

// Settings Tab Actions
export const SET_SETTINGS_TAB = 'SET_SETTINGS_TAB';

// Acounts  / user tab actions
export const SET_ACCOUNTS_USERS_TAB = 'SET_ACCOUNTS_USERS_TAB';

// Volumes Tab actions
// Tab Actions
export const SET_VOLUME_DETAILS_TAB = 'SET_VOLUME_DETAILS_TAB';
export const SET_VOLUMES_TAB = 'SET_VOLUMES_TAB';

// Cluster Tab actions
// Tab actions
export const SET_CLUSTER_DETAILS_TAB = 'SET_CLUSTER_DETAILS_TAB';

// Backup Tab actions
export const SET_BACKUP_TAB = 'SET_BACKUP_TAB';

// Recover Tab actions
export const SET_RECOVER_TAB = 'SET_RECOVER_TAB';

// Auth Actions
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Policy summary
export const GET_SLO_SUMMARY_REQUEST = 'GET_SLO_SUMMARY_REQUEST';
export const GET_SLO_SUMMARY_SUCCESS = 'GET_SLO_SUMMARY_SUCCESS';
export const GET_SLO_SUMMARY_FAILURE = 'GET_SLO_SUMMARY_FAILURE';

// Policy summary
export const GET_SLO_COMPLIANCE_REQUEST = 'GET_SLO_COMPLIANCE_REQUEST';
export const GET_SLO_COMPLIANCE_SUCCESS = 'GET_SLO_COMPLIANCE_SUCCESS';
export const GET_SLO_COMPLIANCE_FAILURE = 'GET_SLO_COMPLIANCE_FAILURE';

// Account Actions
export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';

export const POST_ACCOUNTS_REQUEST = 'POST_ACCOUNTS_REQUEST';
export const POST_ACCOUNTS_SUCCESS = 'POST_ACCOUNTS_SUCCESS';
export const POST_ACCOUNTS_FAILURE = 'POST_ACCOUNTS_FAILURE';

export const DELETE_ACCOUNTS_REQUEST = 'DELETE_ACCOUNTS_REQUEST';
export const DELETE_ACCOUNTS_SUCCESS = 'DELETE_ACCOUNTS_SUCCESS';
export const DELETE_ACCOUNTS_FAILURE = 'DELETE_ACCOUNTS_FAILURE';

export const UPDATE_ACCOUNTS_REQUEST = 'UPDATE_ACCOUNTS_REQUEST';
export const UPDATE_ACCOUNTS_SUCCESS = 'UPDATE_ACCOUNTS_SUCCESS';
export const UPDATE_ACCOUNTS_FAILURE = 'UPDATE_ACCOUNTS_FAILURE';

export const UPDATE_SESSION_ACCOUNT_SUCCESS = 'UPDATE_SESSION_ACCOUNT_SUCCESS';

export const POST_ACCOUNT_PROTECTION_DOMAIN_SET_REQUEST = 'POST_ACCOUNT_PROTECTION_DOMAIN_SET_REQUEST';
export const POST_ACCOUNT_PROTECTION_DOMAIN_SET_SUCCESS = 'POST_ACCOUNT_PROTECTION_DOMAIN_SET_SUCCESS';
export const POST_ACCOUNT_PROTECTION_DOMAIN_SET_FAILURE = 'POST_ACCOUNT_PROTECTION_DOMAIN_SET_FAILURE';

export const POST_ACCOUNT_SNAPSHOT_POLICY_SET_REQUEST = 'POST_ACCOUNT_SNAPSHOT_POLICY_SET_REQUEST';
export const POST_ACCOUNT_SNAPSHOT_POLICY_SUCCESS = 'POST_ACCOUNT_SNAPSHOT_POLICY_SUCCESS';
export const POST_ACCOUNT_SNAPSHOT_POLICY_FAILURE = 'POST_ACCOUNT_SNAPSHOT_POLICY_FAILURE';

// User Actions (supports login/auth)
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Users actions (supports resource mgmt)
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const POST_USERS_REQUEST = 'POST_USERS_REQUEST';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const POST_USERS_FAILURE = 'POST_USERS_FAILURE';

export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE';

export const UPDATE_USERS_REQUEST = 'UPDATE_USERS_REQUEST';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';

// CSP Actions
export const GET_CSPS_REQUEST = 'GET_CSPS_REQUEST';
export const GET_CSPS_SUCCESS = 'GET_CSPS_SUCCESS';
export const GET_CSPS_FAILURE = 'GET_CSPS_FAILURE';

export const POST_CSPS_REQUEST = 'POST_CSPS_REQUEST';
export const POST_CSPS_SUCCESS = 'POST_CSPS_SUCCESS';
export const POST_CSPS_FAILURE = 'POST_CSPS_FAILURE';

export const DELETE_CSPS_REQUEST = 'DELETE_CSPS_REQUEST';
export const DELETE_CSPS_SUCCESS = 'DELETE_CSPS_SUCCESS';
export const DELETE_CSPS_FAILURE = 'DELETE_CSPS_FAILURE';

export const UPDATE_CSPS_REQUEST = 'UPDATE_CSPS_REQUEST';
export const UPDATE_CSPS_SUCCESS = 'UPDATE_CSPS_SUCCESS';
export const UPDATE_CSPS_FAILURE = 'UPDATE_CSPS_FAILURE';

export const REMOVE_SELECTED_ROW_CSPS = 'REMOVE_SELECTED_ROW_CSPS';

export const POST_CSPS_AND_CLUSTER_REQUEST = 'POST_CSPS_AND_CLUSTER_REQUEST';
export const POST_CSPS_AND_CLUSTER_SUCCESS = 'POST_CSPS_AND_CLUSTER_SUCCESS';
export const POST_CSPS_AND_CLUSTER_FAILURE = 'POST_CSPS_AND_CLUSTER_FAILURE';

export const GET_CSP_METADATA_REQUEST = 'GET_CSP_METADATA_REQUEST';
export const GET_CSP_METADATA_SUCCESS = 'GET_CSP_METADATA_SUCCESS';
export const GET_CSP_METADATA_FAILURE = 'GET_CSP_METADATA_FAILURE';

export const GET_PROTECTION_DOMAIN_HISTORY_REQUEST = 'GET_PROTECTION_DOMAIN_HISTORY_REQUEST';
export const GET_PROTECTION_DOMAIN_HISTORY_SUCCESS = 'GET_PROTECTION_DOMAIN_HISTORY_SUCCESS';
export const GET_PROTECTION_DOMAIN_HISTORY_FAILURE = 'GET_PROTECTION_DOMAIN_HISTORY_FAILURE';

// CSP Credential Actions
export const GET_CSP_CREDENTIALS_REQUEST = 'GET_CSP_CREDENTIALS_REQUEST';
export const GET_CSP_CREDENTIALS_SUCCESS = 'GET_CSP_CREDENTIALS_SUCCESS';
export const GET_CSP_CREDENTIALS_FAILURE = 'GET_CSP_CREDENTIALS_FAILURE';

export const POST_CSP_CREDENTIALS_REQUEST = 'POST_CSP_CREDENTIALS_REQUEST';
export const POST_CSP_CREDENTIALS_SUCCESS = 'POST_CSP_CREDENTIALS_SUCCESS';
export const POST_CSP_CREDENTIALS_FAILURE = 'POST_CSP_CREDENTIALS_FAILURE';

export const DELETE_CSP_CREDENTIALS_REQUEST = 'DELETE_CSP_CREDENTIALS_REQUEST';
export const DELETE_CSP_CREDENTIALS_SUCCESS = 'DELETE_CSP_CREDENTIALS_SUCCESS';
export const DELETE_CSP_CREDENTIALS_FAILURE = 'DELETE_CSP_CREDENTIALS_FAILURE';

export const UPDATE_CSP_CREDENTIALS_REQUEST = 'UPDATE_CSP_CREDENTIALS_REQUEST';
export const UPDATE_CSP_CREDENTIALS_SUCCESS = 'UPDATE_CSP_CREDENTIALS_SUCCESS';
export const UPDATE_CSP_CREDENTIALS_FAILURE = 'UPDATE_CSP_CREDENTIALS_FAILURE';

// PD Actions
export const GET_PROTECTION_DOMAINS_REQUEST = 'GET_PROTECTION_DOMAINS_REQUEST';
export const GET_PROTECTION_DOMAINS_SUCCESS = 'GET_PROTECTION_DOMAINS_SUCCESS';
export const GET_PROTECTION_DOMAINS_FAILURE = 'GET_PROTECTION_DOMAINS_FAILURE';

export const POST_PROTECTION_DOMAINS_REQUEST = 'POST_PROTECTION_DOMAINS_REQUEST';
export const POST_PROTECTION_DOMAINS_SUCCESS = 'POST_PROTECTION_DOMAINS_SUCCESS';
export const POST_PROTECTION_DOMAINS_FAILURE = 'POST_PROTECTION_DOMAINS_FAILURE';

export const DELETE_PROTECTION_DOMAINS_REQUEST = 'DELETE_PROTECTION_DOMAINS_REQUEST';
export const DELETE_PROTECTION_DOMAINS_SUCCESS = 'DELETE_PROTECTION_DOMAINS_SUCCESS';
export const DELETE_PROTECTION_DOMAINS_FAILURE = 'DELETE_PROTECTION_DOMAINS_FAILURE';

export const UPDATE_PROTECTION_DOMAINS_REQUEST = 'UPDATE_PROTECTION_DOMAINS_REQUEST';
export const UPDATE_PROTECTION_DOMAINS_SUCCESS = 'UPDATE_PROTECTION_DOMAINS_SUCCESS';
export const UPDATE_PROTECTION_DOMAINS_FAILURE = 'UPDATE_PROTECTION_DOMAINS_FAILURE';

export const GET_PROTECTION_DOMAIN_METADATA_REQUEST = 'GET_PROTECTION_DOMAIN_METADATA_REQUEST';
export const GET_PROTECTION_DOMAIN_METADATA_SUCCESS = 'GET_PROTECTION_DOMAIN_METADATA_SUCCESS';
export const GET_PROTECTION_DOMAIN_METADATA_FAILURE = 'GET_PROTECTION_DOMAIN_METADATA_FAILURE';

export const REMOVE_SELECTED_ROW_PROTECTION_DOMAINS = 'REMOVE_SELECTED_ROW_PROTECTION_DOMAINS';

// CSP Storage Type Actions
export const GET_CSP_STORAGE_TYPES_REQUEST = 'GET_CSP_STORAGE_TYPES_REQUEST';
export const GET_CSP_STORAGE_TYPES_SUCCESS = 'GET_CSP_STORAGE_TYPES_SUCCESS';
export const GET_CSP_STORAGE_TYPES_FAILURE = 'GET_CSP_STORAGE_TYPES_FAILURE';
export const SELECT_CSP_STORAGE_TYPE = 'SELECT_CSP_STORAGE_TYPE';
export const UNMOUNT_CSP_STORAGE_TYPES = 'UNMOUNT_CSP_STORAGE_TYPES';

// Storage Provisioner Actions
export const GET_STORAGE_PROVISIONERS_REQUEST = 'GET_STORAGE_PROVISIONERS_REQUEST';
export const GET_STORAGE_PROVISIONERS_SUCCESS = 'GET_STORAGE_PROVISIONERS_SUCCESS';
export const GET_STORAGE_PROVISIONERS_FAILURE = 'GET_STORAGE_PROVISIONERS_FAILURE';

export const POST_STORAGE_PROVISIONERS_REQUEST = 'POST_STORAGE_PROVISIONERS_REQUEST';
export const POST_STORAGE_PROVISIONERS_SUCCESS = 'POST_STORAGE_PROVISIONERS_SUCCESS';
export const POST_STORAGE_PROVISIONERS_FAILURE = 'POST_STORAGE_PROVISIONERS_FAILURE';

export const DELETE_STORAGE_PROVISIONERS_REQUEST = 'DELETE_STORAGE_PROVISIONERS_REQUEST';
export const DELETE_STORAGE_PROVISIONERS_SUCCESS = 'DELETE_STORAGE_PROVISIONERS_SUCCESS';
export const DELETE_STORAGE_PROVISIONERS_FAILURE = 'DELETE_STORAGE_PROVISIONERS_FAILURE';

export const UPDATE_STORAGE_PROVISIONERS_REQUEST = 'UPDATE_STORAGE_PROVISIONERS_REQUEST';
export const UPDATE_STORAGE_PROVISIONERS_SUCCESS = 'UPDATE_STORAGE_PROVISIONERS_SUCCESS';
export const UPDATE_STORAGE_PROVISIONERS_FAILURE = 'UPDATE_STORAGE_PROVISIONERS_FAILURE';

// Cluster actions
export const GET_CLUSTERS_REQUEST = 'GET_CLUSTERS_REQUEST';
export const GET_CLUSTERS_SUCCESS = 'GET_CLUSTERS_SUCCESS';
export const GET_CLUSTERS_FAILURE = 'GET_CLUSTERS_FAILURE';

export const DELETE_CLUSTERS_REQUEST = 'DELETE_CLUSTERS_REQUEST';
export const DELETE_CLUSTERS_SUCCESS = 'DELETE_CLUSTERS_SUCCESS';
export const DELETE_CLUSTERS_FAILURE = 'DELETE_CLUSTERS_FAILURE';

export const UPDATE_CLUSTERS_REQUEST = 'UPDATE_CLUSTERS_REQUEST';
export const UPDATE_CLUSTERS_SUCCESS = 'UPDATE_CLUSTERS_SUCCESS';
export const UPDATE_CLUSTERS_FAILURE = 'UPDATE_CLUSTERS_FAILURE';

export const GET_CLUSTERS_ACCOUNT_SECRET_REQUEST = 'GET_CLUSTERS_ACCOUNT_SECRET_REQUEST';
export const GET_CLUSTERS_ACCOUNT_SECRET_SUCCESS = 'GET_CLUSTERS_ACCOUNT_SECRET_SUCCESS';
export const GET_CLUSTERS_ACCOUNT_SECRET_FAILURE = 'GET_CLUSTERS_ACCOUNT_SECRET_FAILURE';

export const POST_CLUSTER_REQUEST = 'POST_CLUSTER_REQUEST';
export const POST_CLUSTER_SUCCESS = 'POST_CLUSTER_SUCCESS';
export const POST_CLUSTER_FAILURE = 'POST_CLUSTER_FAILURE';

export const GET_ORCHESTRATOR_DEPLOYMENT_REQUEST = 'GET_ORCHESTRATOR_DEPLOYMENT_REQUEST';
export const GET_ORCHESTRATOR_DEPLOYMENT_SUCCESS = 'GET_ORCHESTRATOR_DEPLOYMENT_SUCCESS';
export const GET_ORCHESTRATOR_DEPLOYMENT_FAILURE = 'GET_ORCHESTRATOR_DEPLOYMENT_FAILURE';
export const GET_ORCHESTRATOR_DEPLOYMENT_UNMOUNT = 'GET_ORCHESTRATOR_DEPLOYMENT_UNMOUNT';

// Node actions
export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS';
export const DELETE_NODES_SUCCESS = 'DELETE_NODES_SUCCESS';
export const UPDATE_NODES_SUCCESS = 'UPDATE_NODES_SUCCESS';

// Resource Utilization Actions
export const GET_RESOURCE_UTILIZATION_REQUEST = 'GET_RESOURCE_UTILIZATION_REQUEST';
export const GET_RESOURCE_UTILIZATION_SUCCESS = 'GET_RESOURCE_UTILIZATION_SUCCESS';
export const GET_RESOURCE_UTILIZATION_FAILURE = 'GET_RESOURCE_UTILIZATION_FAILURE';
export const INVALIDATE_RESOURCE_UTILIZATION = 'INVALIDATE_RESOURCE_UTILIZATION';

// Service Plan Actions
export const GET_SERVICE_PLANS_REQUEST = 'GET_SERVICE_PLANS_REQUEST';
export const GET_SERVICE_PLANS_SUCCESS = 'GET_SERVICE_PLANS_SUCCESS';
export const GET_SERVICE_PLANS_FAILURE = 'GET_SERVICE_PLANS_FAILURE';

export const DELETE_SERVICE_PLANS_REQUEST = 'DELETE_SERVICE_PLANS_REQUEST';
export const DELETE_SERVICE_PLANS_SUCCESS = 'DELETE_SERVICE_PLANS_SUCCESS';
export const DELETE_SERVICE_PLANS_FAILURE = 'DELETE_SERVICE_PLANS_FAILURE';

export const UPDATE_SERVICE_PLANS_REQUEST = 'UPDATE_SERVICE_PLANS_REQUEST';
export const UPDATE_SERVICE_PLANS_SUCCESS = 'UPDATE_SERVICE_PLANS_SUCCESS';
export const UPDATE_SERVICE_PLANS_FAILURE = 'UPDATE_SERVICE_PLANS_FAILURE';

export const ADD_SERVICE_PLAN_COMPARE = 'ADD_SERVICE_PLAN_COMPARE';
export const REMOVE_SERVICE_PLAN_COMPARE = 'REMOVE_SERVICE_PLAN_COMPARE';
export const CLEAR_SERVICE_PLAN_COMPARES = 'CLEAR_SERVICE_PLAN_COMPARES';

export const SET_SERVICE_PLANS_OVERVIEW_TAB = 'SET_SERVICE_PLANS_OVERVIEW_TAB';

// Service Plan Allocations
export const GET_SPA_REQUEST = 'GET_SPA_REQUEST';
export const GET_SPA_SUCCESS = 'GET_SPA_SUCCESS';
export const GET_SPA_FAILURE = 'GET_SPA_FAILURE';

export const POST_SPA_FAILURE = 'POST_SPA_FAILURE';

export const UPDATE_SPA_REQUEST = 'UPDATE_SPA_REQUEST';
export const UPDATE_SPA_SUCCESS = 'UPDATE_SPA_SUCCESS';
export const UPDATE_SPA_FAILURE = 'UPDATE_SPA_FAILURE';

export const DELETE_SPAS_SUCCESS = 'DELETE_SPAS_SUCCESS';
export const DELETE_SPAS_FAILURE = 'DELETE_SPAS_FAILURE';

// Tags actions
export const ADD_TAG = 'ADD_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const MOUNT_TAG = 'MOUNT_TAG';
export const UNMOUNT_TAGS = 'UNMOUNT_TAGS';

// Volume Series Actions
export const GET_VOLUME_SERIES_REQUEST = 'GET_VOLUME_SERIES_REQUEST';
export const GET_VOLUME_SERIES_SUCCESS = 'GET_VOLUME_SERIES_SUCCESS';
export const GET_VOLUME_SERIES_FAILURE = 'GET_VOLUME_SERIES_FAILURE';

export const POST_VOLUME_SERIES_REQUEST = 'POST_VOLUME_SERIES_REQUEST';
export const POST_VOLUME_SERIES_SUCCESS = 'POST_VOLUME_SERIES_SUCCESS';
export const POST_VOLUME_SERIES_FAILURE = 'POST_VOLUME_SERIES_FAILURE';

export const DELETE_VOLUME_SERIES_REQUEST = 'DELETE_VOLUME_SERIES_REQUEST';
export const DELETE_VOLUME_SERIES_SUCCESS = 'DELETE_VOLUME_SERIES_SUCCESS';
export const DELETE_VOLUME_SERIES_FAILURE = 'DELETE_VOLUME_SERIES_FAILURE';

export const UPDATE_VOLUME_SERIES_REQUEST = 'UPDATE_VOLUME_SERIES_REQUEST';
export const UPDATE_VOLUME_SERIES_SUCCESS = 'UPDATE_VOLUME_SERIES_SUCCESS';
export const UPDATE_VOLUME_SERIES_FAILURE = 'UPDATE_VOLUME_SERIES_FAILURE';

export const UPDATE_VOLUME_SERIES_AG = 'UPDATE_VOLUME_SERIES_AG';

export const GET_VSR_REQUEST = 'GET_VSR_REQUEST';
export const GET_VSR_SUCCESS = 'GET_VSR_SUCCESS';
export const GET_VSR_FAILURE = 'GET_VSR_FAILURE';
export const POST_VSR_SUCCESS = 'POST_VSR_SUCCESS';
export const UPDATE_VSR_SUCCESS = 'UPDATE_VSR_SUCCESS';

export const GET_VSR_COMPLETED_REQUEST = 'GET_VSR_COMPLETED_REQUEST';
export const GET_VSR_COMPLETED_SUCCESS = 'GET_VSR_COMPLETED_SUCCESS';
export const GET_VSR_COMPLETED_FAILURE = 'GET_VSR_COMPLETED_FAILURE';

export const GET_VOLUME_SERIES_PV_SPEC_REQUEST = 'GET_VOLUME_SERIES_PV_SPEC_REQUEST';
export const GET_VOLUME_SERIES_PV_SPEC_COMPLETE = 'GET_VOLUME_SERIES_PV_SPEC_COMPLETE';

export const REMOVE_SELECTED_ROW_VOLUME_SERIES_TABLE = 'REMOVE_SELECTED_ROW_VOLUME_SERIES_TABLE';

// Accounts Table Actions
export const UPDATE_ACCOUNTS_TABLE_IDS = 'UPDATE_ACCOUNTS_TABLE_IDS';
export const TABLE_UNMOUNT_ACCOUNTS = 'TABLE_UNMOUNT_ACCOUNTS';

export const UPDATE_ACCOUNT_USER_TABLE_IDS = 'UPDATE_ACCOUNT_USER_TABLE_IDS';
export const TABLE_UNMOUNT_ACCOUNT_USERS = 'TABLE_UNMOUNT_ACCOUNT_USERS';

// Volume metric actions

export const GET_VOLUME_METRICS_REQUEST = 'GET_VOLUME_METRICS_REQUEST';
export const GET_VOLUME_METRICS_SUCCESS = 'GET_VOLUME_METRICS_SUCCESS';
export const GET_VOLUME_METRICS_FAILURE = 'GET_VOLUME_METRICS_FAILURE';
export const CLEAR_VOLUME_METRICS = 'CLEAR_VOLUME_METRICS';

export const GET_VOLUME_CAPACITY_REQUEST = 'GET_VOLUME_CAPACITY_REQUEST';
export const GET_VOLUME_CAPACITY_SUCCESS = 'GET_VOLUME_CAPACITY_SUCCESS';
export const GET_VOLUME_CAPACITY_FAILURE = 'GET_VOLUME_CAPACITY_FAILURE';
export const CLEAR_VOLUME_CAPACITY = 'CLEAR_VOLUME_CAPACITY';

// Storage actions

export const GET_STORAGE_REQUEST = 'GET_STORAGE_REQUEST';
export const GET_STORAGE_SUCCESS = 'GET_STORAGE_SUCCESS';
export const GET_STORAGE_FAILURE = 'GET_STORAGE_FAILURE';

// Storage metrics actions

export const GET_STORAGE_METRICS_REQUEST = 'GET_STORAGE_METRICS_REQUEST';
export const GET_STORAGE_METRICS_SUCCESS = 'GET_STORAGE_METRICS_SUCCESS';
export const GET_STORAGE_METRICS_FAILURE = 'GET_STORAGE_METRICS_FAILURE';
export const CLEAR_STORAGE_METRICS = 'CLEAR_STORAGE_METRICS';

// Compliance metrics

export const GET_ACCOUNT_COMPLIANCE_TOTALS_REQUEST = 'GET_ACCOUNT_COMPLIANCE_TOTALS_REQUEST';
export const GET_ACCOUNT_COMPLIANCE_TOTALS_SUCCESS = 'GET_ACCOUNT_COMPLIANCE_TOTALS_SUCCESS';
export const GET_ACCOUNT_COMPLIANCE_TOTALS_FAILURE = 'GET_ACCOUNT_COMPLIANCE_TOTALS_FAILURE';

export const GET_APPGROUP_COMPLIANCE_TOTALS_REQUEST = 'GET_APPGROUP_COMPLIANCE_TOTALS_REQUEST';
export const GET_APPGROUP_COMPLIANCE_TOTALS_SUCCESS = 'GET_APPGROUP_COMPLIANCE_TOTALS_SUCCESS';
export const GET_APPGROUP_COMPLIANCE_TOTALS_FAILURE = 'GET_APPGROUP_COMPLIANCE_TOTALS_FAILURE';

export const GET_CLUSTER_COMPLIANCE_TOTALS_REQUEST = 'GET_CLUSTER_COMPLIANCE_TOTALS_REQUEST';
export const GET_CLUSTER_COMPLIANCE_TOTALS_SUCCESS = 'GET_CLUSTER_COMPLIANCE_TOTALS_SUCCESS';
export const GET_CLUSTER_COMPLIANCE_TOTALS_FAILURE = 'GET_CLUSTER_COMPLIANCE_TOTALS_FAILURE';

export const GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_REQUEST = 'GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_REQUEST';
export const GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_SUCCESS = 'GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_SUCCESS';
export const GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_FAILURE = 'GET_CONSISTENCYGROUP_COMPLIANCE_TOTALS_FAILURE';

export const GET_SERVICE_PLAN_COMPLIANCE_TOTALS_REQUEST = 'GET_SERVICE_PLAN_COMPLIANCE_TOTALS_REQUEST';
export const GET_SERVICE_PLAN_COMPLIANCE_TOTALS_SUCCESS = 'GET_SERVICE_PLAN_COMPLIANCE_TOTALS_SUCCESS';
export const GET_SERVICE_PLAN_COMPLIANCE_TOTALS_FAILURE = 'GET_SERVICE_PLAN_COMPLIANCE_TOTALS_FAILURE';

export const GET_VOLUME_COMPLIANCE_TOTALS_REQUEST = 'GET_VOLUME_COMPLIANCE_TOTALS_REQUEST';
export const GET_VOLUME_COMPLIANCE_TOTALS_SUCCESS = 'GET_VOLUME_COMPLIANCE_TOTALS_SUCCESS';
export const GET_VOLUME_COMPLIANCE_TOTALS_FAILURE = 'GET_VOLUME_COMPLIANCE_TOTALS_FAILURE';

export const GET_VOLUME_SERVICE_HISTORY_REQUEST = 'GET_VOLUME_SERVICE_HISTORY_REQUEST';
export const GET_VOLUME_SERVICE_HISTORY_SUCCESS = 'GET_VOLUME_SERVICE_HISTORY_SUCCESS';
export const GET_VOLUME_SERVICE_HISTORY_FAILURE = 'GET_VOLUME_SERVICE_HISTORY_FAILURE';

export const GET_VOLUME_STATUS_REQUEST = 'GET_VOLUME_STATUS_REQUEST';
export const GET_VOLUME_STATUS_SUCCESS = 'GET_VOLUME_STATUS_SUCCESS';
export const GET_VOLUME_STATUS_FAILURE = 'GET_VOLUME_STATUS_FAILURE';

export const INVALIDATE_METRICS = 'INVALIDATE_METRICS';

// Alert Message Actions

export const ADD_ALERT_MESSAGE = 'ADD_ALERT_MESSAGE';
export const REMOVE_ALERT_MESSAGE = 'REMOVE_ALERT_MESSAGE';
export const SET_ERROR_MESSAGES = 'SET_ERROR_MESSAGES';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
export const CLEAR_ALL_MESSAGES = 'CLEAR_ALL_MESSAGES';

// Socket Actions

export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';

export const WATCHER_CONNECTED = 'WATCHER_CONNECTED';
export const WATCHER_CONNECTING = 'WATCHER_CONNECTING';
export const WATCHER_DISCONNECTED = 'WATCHER_DISCONNECTED';

// Application Group Actions

export const GET_AG_REQUEST = 'GET_AG_REQUEST';
export const GET_AG_SUCCESS = 'GET_AG_SUCCESS';
export const GET_AG_FAILURE = 'GET_AG_FAILURE';

export const POST_AG_REQUEST = 'POST_AG_REQUEST';
export const POST_AG_SUCCESS = 'POST_AG_SUCCESS';
export const POST_AG_FAILURE = 'POST_AG_FAILURE';

export const DELETE_AG_REQUEST = 'DELETE_AG_REQUEST';
export const DELETE_AG_SUCCESS = 'DELETE_AG_SUCCESS';
export const DELETE_AG_FAILURE = 'DELETE_AG_FAILURE';

export const UPDATE_AG_REQUEST = 'UPDATE_AG_REQUEST';
export const UPDATE_AG_SUCCESS = 'UPDATE_AG_SUCCESS';
export const UPDATE_AG_FAILURE = 'UPDATE_AG_FAILURE';

export const REMOVE_SELECTED_ROW_APPLICATION_GROUPS_TABLE = 'REMOVE_SELECTED_ROW_APPLICATION_GROUPS_TABLE';
export const REMOVE_ALL_SELECTED_ROWS_APPLICATION_GROUPS_TABLE = 'REMOVE_ALL_SELECTED_ROWS_APPLICATION_GROUPS_TABLE';

// Consistency Group Actions

export const GET_CG_REQUEST = 'GET_CG_REQUEST';
export const GET_CG_SUCCESS = 'GET_CG_SUCCESS';
export const GET_CG_FAILURE = 'GET_CG_FAILURE';

export const POST_CG_REQUEST = 'POST_CG_REQUEST';
export const POST_CG_SUCCESS = 'POST_CG_SUCCESS';
export const POST_CG_FAILURE = 'POST_CG_FAILURE';

export const DELETE_CG_REQUEST = 'DELETE_CG_REQUEST';
export const DELETE_CG_SUCCESS = 'DELETE_CG_SUCCESS';
export const DELETE_CG_FAILURE = 'DELETE_CG_FAILURE';

export const UPDATE_CG_REQUEST = 'UPDATE_CG_REQUEST';
export const UPDATE_CG_SUCCESS = 'UPDATE_CG_SUCCESS';
export const UPDATE_CG_FAILURE = 'UPDATE_CG_FAILURE';

export const REMOVE_SELECTED_ROW_CONSISTENCY_GROUPS_TABLE = 'REMOVE_SELECTED_ROW_CONSISTENCY_GROUPS_TABLE';
export const REMOVE_ALL_SELECTED_ROWS_CONSISTENCY_GROUPS_TABLE = 'REMOVE_ALL_SELECTED_ROWS_CONSISTENCY_GROUPS_TABLE';

export const REMOVE_ALL_SELECTED_ROWS_SNAPSHOTS_TABLE = 'REMOVE_ALL_SELECTED_ROWS_SNAPSHOTS_TABLE';

export const SET_DASHBOARD_TIME_PERIOD = 'SET_DASHBOARD_TIME_PERIOD';

export const SET_VOLUME_DETAILS_TIME_PERIOD = 'SET_VOLUME_DETAILS_TIME_PERIOD';

// Roles

export const GET_ROLES_REQUEST = 'GET_ROLES_REQUEST';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';

// System

export const GET_SYSTEM_HOSTNAME_REQUEST = 'GET_SYSTEM_HOSTNAME_REQUEST';
export const GET_SYSTEM_HOSTNAME_SUCCESS = 'GET_SYSTEM_HOSTNAME_SUCCESS';
export const GET_SYSTEM_HOSTNAME_FAILURE = 'GET_SYSTEM_HOSTNAME_FAILURE';

// context

export const SESSION_RELOAD_START = 'SESSION_RELOAD_START';
export const SESSION_RELOAD_DONE = 'SESSION_RELOAD_DONE';

export const METRICS_DATABASE_READY = 'METRICS_DATABASE_READY';
export const METRICS_DATABASE_DISCONNECTED = 'METRICS_DATABASE_DISCONNECTED';

// snapshots
export const GET_SNAPSHOTS_REQUEST = 'GET_SNAPSHOTS_REQUEST';
export const GET_SNAPSHOTS_SUCCESS = 'GET_SNAPSHOTS_SUCCESS';
export const GET_SNAPSHOTS_FAILURE = 'GET_SNAPSHOTS_FAILURE';

// setup
export const SET_SETUP_STEP = 'SET_SETUP_STEP';
export const ADD_SETUP_STEP_COMPLETED = 'ADD_SETUP_STEP_COMPLETED';

// header
export const SET_HEADER_RESOURCE_NAME = 'SET_HEADER_RESOURCE_NAME';

// version

export const GET_VERSION_REQUEST = 'GET_VERSION_REQUEST';
export const GET_VERSION_SUCCESS = 'GET_VERSION_SUCCESS';
export const GET_VERSION_FAILURE = 'GET_VERSION_FAILURE';

// Settings tabs

export const SETTINGS_TAB_ABOUT = 'SETTINGS_TAB_ABOUT';

// version

export const POST_AUDIT_LOG_REQUEST = 'POST_AUDIT_LOG_REQUEST';
export const POST_AUDIT_LOG_SUCCESS = 'POST_AUDIT_LOG_SUCCESS';
export const POST_AUDIT_LOG_FAILURE = 'POST_AUDIT_LOG_FAILURE';

// resource navigation

export const SET_RESOURCE_NAVIGATION_DATA = 'SET_RESOURCE_NAVIGATION_DATA';
